# 11. September: DATA_ROOT_DIR="/home/christopher/Downloads/Databricks" nohup /home/christopher/Development/Python/MultiAgentWorkFlows/.venv/bin/python -u appNew.py > gradio.log 2>&1 &


# 07. Sept. 2026 - pip install mlflow

# 3 september install: python -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

# 31st of August update to Milvus Lite: pip install --upgrade pymilvus milvus-lite

# *********************************************************************************************************

# To run this file locally from the terminal use:
    # run everytime a new terminal with 'mlflow server'
    # export DATA_ROOT_DIR="/home/christopher/Downloads/Databricks"  # OR # python -m appNew.py [--DATA_ROOT_DIR="/home/christopher/Downloads/Databricks"]
    # export GRADIO_SERVER_PORT=7862 # need to set this if we are exposing public link through ngrok 
    # python appNew.py

# *********************************************************************************************************

# To run this from the terminal, but in docker use this
#     #docker run --network="host" -v /home/christopher/Downloads/Databricks:/data rag-milvus-llm-qwen2.5

# docker run --rm \
#   --add-host=host.docker.internal:host-gateway \
#   -e OLLAMA_HOST=http://host.docker.internal:11434 \
#   -e DATA_ROOT_DIR=/data \
#   rag-milvus-llm-qwen2.5:latest
#  ...

# *********************************************************************************************************

# RAG
# The quality of the answers generated by the language model will depend directly on how well the 
# data is prepared, chunked, and indexed.

# to run as notebook 
# pip install --quiet pymupdf databricks-sdk --upgrade databricks-ai-search
# pip install --quiet pandas nltk
# pip install -U pymilvus
# pip install -U "pymilvus[milvus_lite]"
# pip install ollama
# pip install pyarrow

# Restart Python to load newly installed packages
# dbutils.library.restartPython() # dbutils in internal to databricks 

# Milvus Lite vector store
# Use Hugging Face's sentence-transformers, open source embedding generation.

# While Apache Spark natively knows how to handle Parquet binaries through its own Java engine, 
# Pandas relies entirely on external Python libraries —specifically pyarrow —to open Parquet data layout structures on Ubuntu.
import logging
import traceback
import pymupdf
import re
#import databricks.sdk as sdk
#import databricks.ai_search as bvs

import os
import pandas as pd
import nltk
import requests

from pathlib import Path
from pyspark.sql.types import StructType, StructField, StringType, DoubleType
from pyspark.sql import SparkSession  # <-- Added for local use
from nltk.tokenize import sent_tokenize

from sentence_transformers import SentenceTransformer
from pymilvus import MilvusClient, DataType
import ollama

from openai import OpenAI
 
from ollama import Client
import time

import threading
import multiprocessing
import queue
import gradio as gr
import mlflow
import mlflow.system_metrics
import openai

MLFLOW_TRACKING_URI = "http://127.0.0.1:5000"
OLLAMA_BASE_URL = "http://localhost:11434/v1"

BOOL_INCLUDE_YIELD = True # need this to only be true if this is being called as a module from the UI  


# logging files
#logSPARK="error_log_SPARK.txt"
logMILVUS = "error_log_MILVUS.txt"
logLLM = "error_logLLM.txt"
logVECTOR = "error_logVECTOR.txt"
logDOWNLOAD = "error_logDOWNLOAD.txt"
logEMBEDDING = "error_logEMBEDDING"

chunk_size=20
overlap = 10
embedding_dim = 768
RAG_collection_name = "covid_medical_rag_docs"

saveFormat = "parquet"

VECTOR_SEARCH_LIMIT = 5

# 'all-MiniLM-L6-v2' generates 384-dimensional vectors, but only a maximum context length of 512 tokens.
# str_SentenceTransformer = 'BAAI/bge-base-en-v1.5'
# embedding_dim = 768
str_SentenceTransformer = 'all-MiniLM-L6-v2'
embedding_dim = 384

model_LLM ='qwen2.5:latest'

instructionPrompt= ("You are a helpful medical data assistant. Your job is to summarize "
                    "the provided context documents into a single, comprehensive, cohesive answer. "
                    "Only use facts directly mentioned in the context. Do not make up information." )

# dbfs_dir = "/dbfs/FileStore/rag_docs" # use in Databricks platform
# dbfs_dir = "/run/media/christopher/external/FileStore/Databricks/rag_docs" # use on external drive

# print ("\nSetting the following paths")

# Use an environment variable, but fallback to '/data' inside the container
DATA_ROOT = Path(os.getenv("DATA_ROOT_DIR", "/data"))

# Build subdirectories dynamically
dbfs_dir = DATA_ROOT / "rag_docs"                               #Path("~/Downloads/Databricks/rag_docs").expanduser()
# print (f"dbfs_dir direcotory:{dbfs_dir}")

pathRagChunks = DATA_ROOT / "rag_docs" / "tmp" /  "rag_chunks"  #"~/Downloads/Databricks/rag_docs/tmp/rag_chunks"
# print (f"pathRagChunks:      {pathRagChunks}")

milvus_path= DATA_ROOT / "rag_docs" / "local_milvus.db"     #"~/Downloads/Databricks/rag_docs/local_milvus.db"
# print (f"mulvus_path:        {milvus_path}")

# Create directories if they doesn't exist
os.makedirs(dbfs_dir, exist_ok=True)  
os.makedirs(pathRagChunks, exist_ok=True)

str_milvus_path = str(milvus_path)  # milvus will need a string of the path
strPath = str(pathRagChunks)        # spark also needs a string path

# # Configure standard production logging to see output inside Docker logs
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# temporary comment as streamlit can't find it
class MilvusLiteLogFilter(logging.Filter):
    
    def filter(self, record):
        # Catch and silence the benign Milvus Lite AllocTimestamp noise
        if "Exception calling application: Method not implemented!" in record.getMessage():
            if record.exc_info:
                exc_text = "".join(traceback.format_exception(*record.exc_info))
                if "AllocTimestamp" in exc_text:
                    return False  # Do not log this record
        return True

# Apply the filter to the gRPC server logger
grpc_logger = logging.getLogger("grpc._server")
grpc_logger.addFilter(MilvusLiteLogFilter())

# surpress hardware support warning messages
logging.getLogger("faiss.loader").setLevel(logging.WARNING) 
logging.getLogger("sentence_transformers").setLevel(logging.WARNING)

# Silence HTTP request logs from networking libraries
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)

# Tells the library to only look at your local cache folder
os.environ["HF_HUB_OFFLINE"] = "1"

# deal with Hugging Face Hub warnings - we are working locally so they are irrelevant.
os.environ["HF_HUB_VERBOSITY"] = "error"

# Force MLflow to log traces synchronously before the script exits
os.environ["MLFLOW_ENABLE_ASYNC_TRACE_LOGGING"] = "false"

# Possible Document dictionaries for pipeline
documents_covid = {
        "cdc_guidelines.pdf": "https://www.cdc.gov/covid/downloads/hcp/interim-clinical-considerations.pdf",
        "who_guidelines.pdf": "https://www.ncbi.nlm.nih.gov/books/NBK582435/pdf/Bookshelf_NBK582435.pdf",
        "nhs_guidelines.pdf": "https://hscscotland.scot/couch/uploads/file/covid19/1_covid-19-guidance-for-social-or-community-care-and-residential-settings.pdf"
    }

documents_skincare = {
        "Skin_care_101.pdf": "https://cdn-links.lww.com/permalink/ijwd/a/ijwd_1_1_2023_07_10_kimball_ijwd-d-22-00059_sdc0.pdf",
        "Colleges_of_Nursing.pdf": "https://www.aacnnursing.org/Portals/0/PDFs/Publications/Essentials-2026.pdf",
        "Oxford_Health_Trust.pdf": "https://www.oxfordhealth.nhs.uk/wp-content/uploads/sites/51/2025/09/2.-The-Skin.pdf"
    }

documents_elderlycare = {
        "Nice_org.pdf": "https://www.nice.org.uk/guidance/ng22/evidence/full-guideline-pdf-552742669"
    }


Global_documents = documents_elderlycare # this can be changed by the user
   

# Define chunking logic with overlap
def chunk_text(text, chunk_size=200, overlap=50):
    """
    Split text into overlapping chunks based on sentence boundaries.

    Returns:
        list: List of text chunks
    """
    print("\nIn chunk_text")
    
    try:
        chunks = []
        current_chunk = []
        current_length = 0
        
        # split the text into sentences
        sentences = sent_tokenize(text)

        for sentence in sentences:
            
            # split each sentence into words
            words = sentence.split()
            sentence_len = len(words)

            # If adding this sentence exceeds chunk size, save current chunk
            if current_length + sentence_len > chunk_size:
                chunks.append(" ".join(current_chunk))
                
                # Keep last 'overlap' words for context continuity
                current_chunk = current_chunk[-overlap:] if overlap else []
                current_length = sum(len(s.split()) for s in current_chunk)

            current_chunk.extend(words)
            current_length += sentence_len

        # Add the final chunk if it exists
        if current_chunk:
            chunks.append(" ".join(current_chunk))

        return chunks
    
    except Exception as e:
            print(f"Error Type: {type(e).__name__}")
            print(f"Error Message: {e}")
            return []


# Utility: Clean extracted text
def clean_text(text):
    """
    Clean extracted PDF text by removing noise and normalizing formatting.

    Args:
        text (str): Raw text extracted from PDF

    Returns:
        str: Cleaned text ready for chunking
    """
    #logger.info("Starting text data cleaning routines...")
    
    # Remove excessive line breaks
    text = re.sub(r"\n+", "\n", text)
    
    # Remove excessive whitespace
    text = re.sub(r"\s{2,}", " ", text)
    
    # Remove page number artifacts
    text = re.sub(r"Page \d+", "", text, flags=re.IGNORECASE)
    
    # Strip out the [image] markers and replace them with a space
    text = text.replace("[image]", " ")

    # Clean up any accidental double spaces caused by the removal
    text = " ".join(text.split())
    
    # Match any digit(s) followed by a period that comes right after a space or sentence end
    # Example matched: " This is a sentence. 1. This is the next item."
    pattern = r"\b\d+\.\s+"
    text = re.sub(pattern, "", text)
    
    # Replace the bullet symbol with a comma and a space
    text = text.replace(" • ", ", ")
    
    # Replace the bullet symbol with a comma and a space
    text = text.replace("", "")
     
    # we dont need commas after a colon
    text = text.replace(":,", ":")
    
    # we dont need commas after a fullstop
    text = text.replace(".,", ".")
    
    # typically a contents section ends up with a long series of dots, or spaces
    text = re.sub(r"\.{2,}", ".", text)
    text = re.sub(r" {2,}", ".", text)
    
    # does this remove content type indexes?
    text = re.sub(r"\d+\s+.*?\s+\.\s+\d+", "", text)
        
    return text.strip()


# Utility: Extract text from PDF using PyMuPDF
def extract_pdf_text(pdf_path):
    """
    Extract text from PDF, clean and return contents as text.
    Report raw compared with clean text statistics.
    """
    try:
        print("\nin extract_pdf_text")
        print(f"PDF: {pdf_path}")
        
        doc = pymupdf.open(pdf_path)
        
        print(f"Pages: {len(doc)}")
        
        metadata = doc.metadata
        doc_date = metadata["creationDate"]
        mod_date = metadata["modDate"]
        print(f"date of pdf is: {doc_date}, modification date is: {mod_date}")
        
        full_text = ""
        for page_number, page in enumerate(doc, start=1):
            page_text = page.get_text()
            full_text += page_text

            # # Show statistics for the first few pages
            # if page_number <= 3:
            #     print(
            #         f"Page {page_number}: "
            #         f"{len(page_text)} characters"
            #     )

        print(f"RAW extracted characters: {len(full_text)}")
        
        cleaned_text = clean_text(full_text)

        print(f"CLEANED characters: {len(cleaned_text)}")
        doc.close()
        return cleaned_text

    except Exception as e:
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        return " "
    
  
def download_and_prepare():
    """_summary_

    Args:
        documents (list): A list of filenames and documents url
        
        Returns a list of documents, and their content as text. This list of documents is then ready to be chunked
    """
    try:
        documents_to_chunk = []
        
        # Download each pdf
        for filename, url in Global_documents.items():
            print(f"\ndownload file: {filename}...")
            # response = requests.get(url)
            response = requests.get(url, timeout=30)
            response.raise_for_status()
            print(f"Length of downloaded pdf file content: {len(response.content)}")
            
            # save each pdf
            full_path = os.path.join(dbfs_dir, filename)
            print(f"saving pdf: {full_path}")
            with open(full_path, "wb") as f:
                f.write(response.content)
            
            # open each pdf again, this time convert the contents to text
            extracted_text = extract_pdf_text(full_path) 
            
            # save text from each pdf as a text file
            # txt_filename = str(filename).rstrip('.pdf') + "_clean.txt"
            txt_filename = os.path.splitext(filename)[0] + "_clean.txt"
            txt_path = os.path.join(dbfs_dir, txt_filename)
            #print(f"Saving cleaned text: {txt_path}")
            with open(txt_path, "w", encoding="utf-8") as f:
                f.write(extracted_text)       
                
            print(f"File {txt_filename} saved.")
            
            # Document metadata structure
            documents_to_chunk.append({"source": str(filename), "text": extracted_text, "publication date": 0})
            print(f"{filename}: cleaned text is ready for later chunking")
            extracted_text = ""
            
        return documents_to_chunk
    
    except Exception as e:
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        return []    
    

def do_chunking(documents_to_chunk, chunk_size=100, chunk_overlap=50):  
    
    """_summary_
    Receives input of a list of individual documents in the following form:
    {"source": str(txt_filename), "text": extracted_text, "publication date": 0}
    
    Returns:
    
    """

    try: 
        # Beginning chunking for all documents
        all_chunks = []
        for doc in documents_to_chunk:
            # call helper function
            print(f"Chunking for {doc["source"]} beginning")
            chunks = chunk_text(doc["text"], chunk_size, chunk_overlap)
                    
            # Ensure your DataFrame column names match 
            # all_chunks need to have these columns 'source','chunk_id','text'
            for i, chunk in enumerate(chunks):
                all_chunks.append({
                    "source": doc["source"],
                    "chunk_id": i,
                    "text": chunk
                })
            
            # all_chunks created by do_chunking routine: {"source": doc["source"], "chunk_id": i, "text": chunk}
            print(f"Chunking Statistics:")
            print(f"{doc["source"]} Total chunks created: {len(chunks)}")             
            print("\n" + "="*30)
                        
        return all_chunks
            
    except Exception as e:
        print("\n" + "="*40 + " ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
        
        return[]
    

def save_Chunks_To_Disk(all_chunks, strPath, saveFormat="delta"): 
    """_summary_

    Args:
        all_chunks (_type_): _description_
        strPath (_type_): _description_
        saveFormat (str, optional): _description_. Defaults to "delta".

    Returns:
        _type_: _description_
    """
    try:
        # Convert to all chunks to a Spark DataFrame and save as Parquet, although
        # it would be better to use Delta rather than Parquet for subsequent Databricks Integration: 
        # ACID Transactions & Protection Against Crashes: Delta is highly resilient. 
        
        # 1. Manually initialize the spark session locally
        # spark = SparkSession.builder.appName("NoDatabricks_onlyLocal").getOrCreate()
        # running locally so reduce concurrent spark writers from 8 parallel writers to 4 
        
        spark = SparkSession.builder.appName("onlyLocal").config("spark.driver.memory", "4g").getOrCreate()

        chunk_df = pd.DataFrame(all_chunks)
        spark_df = spark.createDataFrame(chunk_df)

        #spark_df.write.mode("overwrite").format("delta").save(pathRagChunks)
        spark_df.write.mode("overwrite").format(saveFormat).save(strPath) # strPath points to pathRagChunks

        print(f"\nChunking complete and saved at: {strPath}")
        print("\n" + "="*30)
        
        # Read the data using the running Spark session
        print("Loading Parquet data using Spark...")
        spark_df = spark.read.parquet(strPath)
    
        # Safely convert to a standard Pandas DataFrame (ignores backend Arrow extension bugs)
        df = spark_df.toPandas()
        # print("Quick look ito data frame before saving")
        # print(df.head(2))
          
        # Ensure your DataFrame column names match 
        # all_chunks created by do_chunking routine: {"source": doc["source"], "chunk_id": i, "text": chunk}
        chunk_texts = df["text"].tolist()       # we only want to return the texts for the embeddings
        chunk_sources = df["source"].tolist()   # we need these as a separate list for the later use of zip
        chunk_ids = df["chunk_id"].tolist()
        #chunks_list = df.values.tolist()       # this we will need to later combine with the new embeddings
        print(f"Successfully loaded {len(chunk_texts)} text chunks.")
        return chunk_texts, chunk_sources, chunk_ids
        
    except Exception as e:
        print("\n" + "="*40 + " In save_Chunks_To_Disk - ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
        
milvus_client = None
        #milvus_client = start_Milvus(collection_name, str_milvus_path, embedding_dim)
        
           
def start_Milvus(collection_name, str_milvus_path, embedding_dim):
    # https://milvus.io/docs/schema.md
    try:
        print("\nIn start_Milvus....")
        
        # need to create a schema rather than relying on Milvus to create the default one as that would consist of just vector and PK
        # schema needed
        # id       primary key
        # vector   FLOAT_VECTOR
        # text     VARCHAR
        # source   VARCHAR
        
        schema = MilvusClient.create_schema()
        
        schema.add_field(
            field_name="id",
            datatype=DataType.INT64,
            is_primary=True,
            auto_id=False,
        )
        schema.add_field(
            field_name="vector",
            datatype=DataType.FLOAT_VECTOR,
            dim=embedding_dim
        )
        schema.add_field(
            field_name="text",
            datatype=DataType.VARCHAR,
            max_length=16384
        )
        schema.add_field(
            field_name="source",
            datatype=DataType.VARCHAR,
            max_length=512
        )
        
        # Initialize Milvus Lite
        print("Connecting to local Milvus Lite...")
        milvus_client = MilvusClient(str_milvus_path)
        
        # Drop if it already exists to prevent duplication errors during development
        if milvus_client.has_collection(collection_name):
            milvus_client.drop_collection(collection_name)
            print("\n dropping existing collection")
            
        milvus_client.create_collection(
            collection_name=collection_name,
            schema=schema
        )
        print(f"Created Milvus collection: {collection_name}")
                
        return milvus_client
        
        
        # index_params = milvus_client.prepare_index_params()
        # index_params.add_index(
        #     field_name="source",
        #     index_type="AUTOINDEX",
        #     index_name="publisher_index"
        # )
        
        # # Index `embedding` with AUTOINDEX and specify metric_type
        # index_params.add_index(
        #     field_name="vector",
        #     index_type="AUTOINDEX",  # Use automatic indexing to simplify complex index settings
        #     metric_type="COSINE"  # Specify similarity metric type, options include L2, COSINE, or IP
        # )
        # milvus_client.create_collection(
        #     collection_name=collection_name,
        #     schema=schema,
        #     index_params=index_params
        # )
        
        
    
    except Exception as e:
        print("\n" + "="*40 + " In start_Milvus - ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
        
        return None



def generate_embeddings(texts_list):
    try:
    
        # Generate the Vector Embeddings
        print("\n" + "="*30)
        print("Generating text embeddings (this may take a moment)...")
        
        # Initialize the local Embedding Model 
        print("\nInitializing sentence-transformers model...")
                
        # Force the Hugging Face transformer model to run strictly on CPU, GPU too small
        model = SentenceTransformer(str_SentenceTransformer, device='cpu')
        embeddings = model.encode(texts_list, show_progress_bar=True)
        # query_vector = model.encode(user_question).tolist()
        
        print("...text embeddings generated.")
        return embeddings
    
    except Exception as e:
        print("\n" + "="*40 + " In generate_embeddings - ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
        return None
            

def save_embeddings_in_vectorstore(chunk_texts_only, chunk_sources, chunk_ids, embeddings):   
    try:
        insert_result = False
        print("\nIn save_embeddings_in_vectorstore")
        
        
        # Warm up Milvus - using helper start_Milvus
        milvus_client = None
        milvus_client = start_Milvus(RAG_collection_name, str_milvus_path, embedding_dim)
        
              
        # Prepare and Insert Data
        print("\nFormatting data for Milvus Lite...")
        
        data_to_insert = []
        # print(f"Number of texts chunks: {len(chunk_texts_only)}")
        # print(f"Number of sources in chunks:{len(chunk_sources)}")
        # print(f"Number of chunk_ids:{len(chunk_ids)}")
        #print(f"{chunk_texts_only[0][:50]}, {chunk_ids[0]}, {chunk_sources[0]}")
        for chunk_id, text, source, vector in zip(chunk_ids, chunk_texts_only, chunk_sources, embeddings):
            data_to_insert.append({
                "id": chunk_id,
                "vector": vector.tolist(),
                "text": text,
                "source": source
            })
        
        print(f"Number of records prepared: {len(data_to_insert)}")
        # print(data_to_insert[0].keys())
        # print(data_to_insert[0]["id"])
        # print(data_to_insert[0]["source"])
        # print(data_to_insert[0]["text"][:50])
        # print(len(data_to_insert[0]["vector"]))
        print(".....  inserting into Milvus Lite...")
        
        insert_result = milvus_client.insert(collection_name=RAG_collection_name, data=data_to_insert)
    
        print(f"\nPipeline complete! Successfully inserted all records into Milvus Lite.")
        #print("\n" + "="*30)
        
        return insert_result
                
    except Exception as e:
        print("\n" + "="*40 + "In save_embeddings_in_vectorstore - ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
        
        return False
    
def experimentRun(system_instruction: str, user_prompt: str, experiment_Name = "Medical_RAG") -> bool:
    
    try:
        
        # print(f"in experiementRun\n. System_instruction:{system_instruction}\n")
        # print(f"in experiementRun. User_prompt:{user_prompt}\n")
        
        # 1. Instantiate a client                    
        # target the host machine - needed for docker
        ollama_host = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1")
        
        # Configure OpenAI client to point to local Ollama server
        #client = Client(host=ollama_host)
        client = openai.OpenAI(
            base_url=ollama_host,
            api_key="ollama"  # A placeholder string 
        )
        
        
        # Invoke the model inside an MLflow run
        with mlflow.start_run(run_name = experiment_Name):
            
            mlflow.log_params({"temperature": "0.5", 
                    "max_tokens": "1000", 
                    "latency_ms":True, 
                    "promptTokens":True, 
                    "model_type":True, 
                    "fast_inference":True, 
                    "completion_tokens":True, 
                    "prompt_tokens_details":True,
                    "completion_tokens_details": True, 
                    "prompt_tokens_details": True,
                    "moderation": True})
            
            
                                
            # # Request the completion with stream=True            
            # response_stream = client.generate( !!! this is the old method
            #     model=model_LLM,
            #     prompt=user_prompt,
            #     system=system_instruction,
            #     stream=True, 
            # )
            # Request the completion with stream=True
            response_stream = client.chat.completions.create( # this is the official new method
                model=model_LLM,
                messages=[  {"role": "system", "content": system_instruction},
                            {"role": "user", "content": user_prompt}],
                stream=True, 
                stream_options={"include_usage": True},
            )

        #     print("\n" + "="*30 + " SUMMARISED RESPONSE " + "="*30 + "\n")
        
            strAnswer = ""
            #  the returned stream yields objects, not dictionaries like the old method
            for chunk in response_stream:
                if chunk.choices and len(chunk.choices) > 0:
                    delta = chunk.choices[0].delta.content
                    if delta: # check against None values
                        strAnswer += delta
                        print(delta, end='', flush=True)
            
            
            print("\n\n" + "="*87)
            print(f"\nHere is the answer repeated:{strAnswer}\n")
                           
            # let's get the trace details for the experiment
            try:
                trace_id = mlflow.get_last_active_trace_id() # Retrieve the trace ID generated automatically by OpenAI autolog
                        
                # 7. Retrieve the complete trace object from the backend
                if trace_id:
                    print("\n\nTrace ID Successfully Captured:", trace_id)
                    time.sleep(1.5) # Add a pause to give the background logger time to flush the data
                    trace = mlflow.get_trace(trace_id)
                    print("Trace Object Details:", trace)
                    
                    status = getattr(trace.info, "state", "UNKNOWN")
                    
                    # Extract latency metrics 
                    latency_ms = getattr(trace.info, "execution_duration", 0)
                    latency_sec = latency_ms / 1000 if latency_ms else 0
                    
                    # promptTokens = getattr(trace.info, "prompt_tokens", 0) # this never works!!
                    # completionTokens = getattr(trace.info, "completion_tokens", 0)
                    
                    # C. Extract the model name from the root span attributes
                    root_span = trace.data.spans[0] 
                    model_name = root_span.attributes.get("model", "Unknown Model")
                    full_request = trace.data.request
                    full_response = trace.data.response
                            
                    # 3. Print out metrics
                    #print(f"\n[Trace ID]: {trace_id}")
                    print(f" Model Involved: {model_name}")
                    print(f" Status: {status}")
                    print(f" Total Latency: {latency_ms} ms ({latency_sec:.2f} seconds)")
                    #print(f" Completion Tokens: {completionTokens}")
                    print(f" Full requests:{full_request}\n")
                    print(f" Full response:{full_response}\n")
                    #print(f" Prompt token count: {promptTokens}\n")
                else:
                    print("\nNo active trace ID recorded by autologger.")      
                                        
            except Exception as e:
                    print(f"\n[ERROR in experimentRun collecting Trace Info] Python crashed with: {e}", file=sys.stderr)
                    return False   
                
        return True, strAnswer    # if we got this far, everything went OK
         
    except Exception as e:
        print("\n" + "="*40 + " Error in experimentRun ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
        return False, ""

    
def main_download_prepare_chunk():
    try:  
        
        print("\n" + "="*30)
        print("\nDownloading and cleaning all docs")
        print("\n" + "="*30)
        
        # BRINGS BACK A LIST OF DOCUMENTS WITH SOURCES 
        documents_to_chunk = []   
        documents_to_chunk = download_and_prepare()
        
        print("\n" + "="*30) 
        print("\nChunking all Docs")  
        print("\n" + "="*30)
    
        # ALL_CHUNKS IS A LIST OF CHUNKS IN THE FOLLOWING FORM: "source","chunk_id","text"
        all_chunks = do_chunking(documents_to_chunk, chunk_size, overlap)
               
        print(f"*** Total chunks created across all documents: {len(all_chunks)} ***\n")
                      
        return "Success", all_chunks     
    
    except Exception as e:
        print("\n" + "="*40 + " ACTUAL ERROR CAUGHT " + "="*40)
        print("\nError Downloading, cleaning and creating text chunks")
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
                
        with open(logDOWNLOAD, "w") as log_file:
            traceback.print_exc(file=log_file)
        print(f"\n[INFO] Full error log has also been saved to {logDOWNLOAD}.")  
        
        return "Failure", []
    
            
def main_generate_vectors_and_save(all_chunks, msg_Q=None):      
    try: 
    
        # chunk_texts_only  = save_Chunks_To_Disk(all_chunks, strPath, saveFormat)
        chunk_texts_only, chunk_sources, chunk_ids = save_Chunks_To_Disk(all_chunks, strPath, saveFormat)
         
        msg_Q.put("Generating embeddings....this could take a couple of minutes.")
        # At the moment we are passing too much into this function, we don't want the chunks_list because it contains more than just text
        
        # Force the Hugging Face transformer model to run strictly on CPU, GPU too small
        # model = SentenceTransformer(str_SentenceTransformer, device='cpu')
        embeddings = None
        embeddings = generate_embeddings(chunk_texts_only) # we are deliberately only passing the texts into here
        
        insert_result = False
        # THE EMBEDDINGS NEED TO BE COMBINED WITH THE all_chunks (original text, id and source), and then everything can be added to the collection
        msg_Q.put("Saving embeddings in Vector store")
        insert_result = save_embeddings_in_vectorstore (chunk_texts_only, chunk_sources, chunk_ids, embeddings)
        
        if insert_result:
            return "Success"
    
    except Exception as e:
            print("\n" + "="*40 + " ACTUAL ERROR CAUGHT " + "="*40)
            print("\nError creating and saving embeddings")
            print(f"Error Type: {type(e).__name__}")
            print(f"Error Message: {e}")
            print("="*100)
                    
            with open(logEMBEDDING, "w") as log_file:
                traceback.print_exc(file=log_file)
            print(f"\n[INFO] Full error log has also been saved to {logEMBEDDING}.") 
            return "Failure"
        
        
def main_search_embeddings(user_question, search_limit=5):
    try: 
        #pass
        
        print("\n" + "="*30)
        print("\nAbout the transform user question into vector, search vector store, and build contexts")            
        print (f"** User question, seeking information for: {user_question} ***\n")
        
        # Vectorize the question using the same transformer model
        # Force the Hugging Face transformer model to run strictly on CPU, GPU too small
        model = SentenceTransformer(str_SentenceTransformer, device='cpu')
        # query_vector = model.encode(user_question).tolist()
        query_vector = model.encode(user_question)
        
        
        # Query local Milvus Lite collection
        print("Connecting to local Milvus Lite to search for relevant chunks...")
        
        milvus_client = MilvusClient(str_milvus_path)
        
        search_results = milvus_client.search(
            collection_name=RAG_collection_name,
            data=[query_vector],
            limit=search_limit,                         # Retrieve the top closest matching chunks
            output_fields=["source","text","id"]        # Ask Milvus to return the original text and it's source
        )
                               
        for hits in search_results:
            print("TopK results:\n")
            for hit in hits:
                #print(f"id:{hit['id']}")
                print(f"distance:{round(hit['distance'],4)}")
                print(f"text:{hit['entity']['text']}")
                print(f"source:{hit['entity']['source']}")
                print("="*63)

        # Prepare Milvus Lite search hits for use by LLM
        retrieved_contexts = []
        for hits in search_results:
            for hit in hits:
                # Collect the raw text chunks discovered by your search
                retrieved_contexts.append(hit['entity']['text'])

        # Join the context blocks with clear dividers
        combined_context = "\n\n---\n\n".join(retrieved_contexts)
                
        #
        #       Searching Vectors for answer to question complete, so context are available for LLM
        #
        
        # msg_Q.put("Vectors searched and context built")
        print("\nVectors searched and context built")
        return "Success", combined_context
        
    except Exception as e:
        print("\n" + "="*40 + "Error main_search_embeddings - ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
                
        with open(logVECTOR, "w") as log_file:
            traceback.print_exc(file=log_file)
        print(f"\n[INFO] Full error log has also been saved to {logVECTOR}.")
        return "Failure", None
    
    
        
def main_summarise_reply(context, user_question):
    try:
        
        os.environ["MLFLOW_ENABLE_ASYNC_TRACE_LOGGING"] = "false" # Force MLflow to log traces synchronously before the script exits
        ollama_url = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1") # Read from the environment variable ("OLLAMA_BASE_URL" will exist in the Docker gateway), or fall back to localhost if it doesn't exist
        
        # MLFlow tracking configurations
        # This automatically detects the Docker environment variable or falls back to local
        tracking_uri = os.getenv("MLFLOW_TRACKING_URI", "http://127.0.0.1:5000")
        mlflow.set_tracking_uri(tracking_uri)
                       
        system_instruction_uri = "MultiAgentWorkFlow_Instruction_Prompt"
                 
        user_prompt_uri = "MultiAgentWorkFlow_User_Prompt" 
                          
        mlflow.openai.autolog() # 2. Enable MLflow autologging for OpenAI client   
        
        system_instructions_template = mlflow.genai.load_prompt (system_instruction_uri)
        system_instructions = system_instructions_template.format()
        
        user_prompt_template = mlflow.genai.load_prompt (user_prompt_uri)
        variables = {"user_question": user_question, "context": context}
        user_prompt = user_prompt_template.format(**variables)
       
        boolRes, strAnswer = experimentRun(system_instructions, user_prompt) # this will capture the call and results
        return boolRes, strAnswer
    except Exception as e:
        print("\n" + "="*40 + " ACTUAL ERROR CAUGHT " + "="*40)
        print("\nError while sending question and contexts to llm for summary")
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
                
        with open(logLLM, "w") as log_file:
            traceback.print_exc(file=log_file)
        print(F"\n[INFO] Full error log has also been saved to {logLLM}.")   
        return "Failure", ""     
    
    
 
# run this straight away if it's just being run as a script, if not hold back because this script is probably being imported by the UI 
def all_main_pipeline(msg_queue=None, selection_x=None):

    """
    Actual main routine in its own thread. 
    Sends updates to UI via a Queue.
    """  
    
    try:    
        all_chunks = []       
        str_Progress = ""
        
        status_msg = "Downloading reference PDFs"
        if msg_queue:
            msg_queue.put(status_msg)  # Send to Q
        else:
            print(f"[Standalone]: {status_msg}")  # Standalone fallback
        
        
        str_Progress, all_chunks = main_download_prepare_chunk()
                
        status_msg = "Generating text chunks"
        if msg_queue:
            msg_queue.put(status_msg)  # Send to Q
        else:
            print(f"[Standalone]: {status_msg}")  # Standalone fallback
                                
        str_Progress = main_generate_vectors_and_save(all_chunks, msg_queue) 
        
        status_msg = "Searching Vectors to answer user question"
        if msg_queue:
            msg_queue.put(status_msg)  # Send to Q
        else:
            print(f"[Standalone]: {status_msg}")  # Standalone fallback  
   
   
    except Exception as e:
        msg_queue.put(f"ERROR: {str(e)}")
        print("\n" + "="*40 + " In all_main_pipeline ACTUAL ERROR CAUGHT " + "="*40)
        print(f"Error Type: {type(e).__name__}")
        print(f"Error Message: {e}")
        print("="*100)
                
        with open(logLLM, "w") as log_file:
            traceback.print_exc(file=log_file)
        print(F"\n[INFO] Full error log has also been saved to {logLLM}.")   
        return "Failure", ""     
    finally:
        msg_queue.put(None)


def ui_pipeline_wrapper():
    
    """Runs the pipeline thread and yields status to the UI."""
    msg_queue = multiprocessing.Queue()
    
    # selection_x = "Skin Care"
     
    # Spin up an entirely separate OS process for the main routine
    process = multiprocessing.Process(target=all_main_pipeline, args=(msg_queue,))
    process.start()
    
    # # Run pipeline in a concurrent thread
    # thread = threading.Thread(target=all_main_pipeline, args=(msg_queue,))
    # thread.start()
    
    final_result = ""
    while True:
        try:
            msg = msg_queue.get(timeout=0.1)
            if msg is None:
                break
            final_result = msg
            yield msg, gr.update(visible=False), gr.update(visible=False), gr.Button("Run Pipeline Once", interactive = False) # Keep LLM section hidden while running
        except queue.Empty:
            continue
            
            
    # Wait for the subprocess to finish its work
    process.join(timeout=30) # Wait up to 60 seconds for it to finish cleanly

    # Terminate it forcefully if it hung, just to be completely safe
    if process.is_alive():
        process.terminate()
        process.join()

    # PIPELINE FINISHED:
    # must be a yield rather than a return because the first use of yield in the while statement, turns this whole function into a generator. 
    yield f"Pipeline Complete!", final_result, gr.update(visible=True), gr.Button("Run Pipeline Once", interactive = False)  


    
def query_llm_worker(user_question, res_queue):
    """Isolated process worker to handle vector search and LLM completion."""
    # Ensure environment vars prevent thread-locking inside this fork
    import os
    os.environ["OMP_NUM_THREADS"] = "1"
    os.environ["MKL_NUM_THREADS"] = "1"
    
    try:
        # Perform embedding lookup and summarize
        # res_queue.put("generating embedding for user question, and searching in vector\n")
        str_Progress, combined_context = main_search_embeddings(user_question, VECTOR_SEARCH_LIMIT)
        
        # res_queue.put("sending the results to the LLM for summary\n")
        str_Progress, final_summary_answer = main_summarise_reply(combined_context, user_question) 
        
        # Disconnect from Milvus before closing the process
        try:
            from pymilvus import connections
            connections.disconnect("default") # dont want to leave the connection haning around
        except Exception:
            pass
            
        res_queue.put(final_summary_answer) # the only thing that we want to write to the queue because it ends up in the LLM answer box
    except Exception as e:
        res_queue.put(f"Error during query: {str(e)}")
    

#def main_query_llm(pipeline_context, user_question):
def main_query_llm(user_question):
    
    res_queue = multiprocessing.Queue() # different Q from the pipeline one
    
    # Spawn an isolated process for the second sentence-transformer call
    query_proc = multiprocessing.Process(target=query_llm_worker, args=(user_question, res_queue))
    query_proc.start()
    
    """ # code below might come in handy if a new text box was needed for info messages
    # at the moment the LLM output box is reserved for just LLM output so we won't be writing adhoc messages to it
    while True:
        try:
            msg = res_queue.get(timeout=0.1)
            if msg is None:
                break
            final_result = msg
            # yield msg, gr.update(visible=False), gr.update(visible=False), gr.Button("Run Pipeline Once", interactive = False) # Keep LLM section hidden while running
        except queue.Empty:
            continue """
    
    
    # Wait for the answer and safely clean up
    query_proc.join(timeout=40)
    
    if query_proc.is_alive():
        query_proc.terminate()
        query_proc.join()
        return "Error: The query process timed out."
        
    try:
        final_summary_answer = res_queue.get_nowait()
    except Exception:
        final_summary_answer = "Error: Failed to retrieve answer from pipeline process."
        
    return f"{final_summary_answer}"

 

def ui_theme_change(selection_x):
    
    print(f"In ui_theme_change, selection: {selection_x}")
    
    global Global_documents
      
    # Match the day to predefined patterns
    match selection_x:
        case "Skin Care":
            Global_documents = documents_skincare
        case "Covid-19":
            Global_documents = documents_covid
        case "Care for the Elderly":
            Global_documents = documents_elderlycare
        case _:
            print("Theme Selection NOT GOOD! Swapping to default")  # Default case
            Global_documents = documents_elderlycare
   
    print(f"User selection, first document in dictionary: {Global_documents}") 
     
    return f"You selected: {selection_x}"


        
with gr.Blocks() as demo:
    gr.Markdown("Data Pipeline & LLM Query Interface")

    # This hidden component stores data behind the scenes across multiple user queries
    pipeline_state = gr.State()
            
    # THE PIPELINE (Runs Once) ---
    with gr.Group() as app:
        gr.Markdown("Start here: Build Data Pipeline: Please choose your topic of interest:")
                
        flavor_dropdown = gr.Dropdown(
            choices=["Skin Care", "Covid-19", "Care for the Elderly"], 
            label="Choose a theme",
            value="Care for the Elderly"  # Default selection
        )
        theme_output_text = gr.Textbox(label="Your Selection")
        pipeline_status = gr.Textbox(label="Pipeline Status", value="Ready to process data.")
        run_pipeline_btn = gr.Button("Run Pipeline Once", variant="primary")
        
    # --- LLM QUERY (Hidden until Pipeline finishes) ---
    with gr.Group(visible=False) as llm_section:
        gr.Markdown("Please ask your question")
        user_query_input = gr.Textbox(label="Your Query", placeholder="Ask something about the processed data...")
        llm_output = gr.Textbox(label="LLM Response")
        submit_query_btn = gr.Button("Ask LLM", variant="secondary")

    # --- UI INTERACTION LOGIC ---
    
    # 1. Clicking the pipeline button updates the status box, saves data to state, and reveals the LLM section
    run_pipeline_btn.click(
        fn=ui_pipeline_wrapper, 
        outputs=[pipeline_status, pipeline_state, llm_section, run_pipeline_btn]
    )
    
    # 2. Clicking the query button reads from the saved state and the textbox, outputting only to the LLM response box
    submit_query_btn.click(
        fn=main_query_llm,
        inputs=[user_query_input], # used to include the pipeline_state
        outputs=[llm_output]
    )
    
    flavor_dropdown.change(
        fn=ui_theme_change, 
        inputs=flavor_dropdown, 
        outputs=theme_output_text
    )


if __name__ == "__main__":
             
    #demo.launch(server_name="127.0.0.1", server_port=7862) # only need a fixed port for ngrok to target
    demo.launch()


            
    # if __name__ == "__main__":  
            
    #     # toggle between UI mode and Standalone mode
    #     RUN_AS_UI = True 
    #     # RUN_AS_UI = False
        
    #     if RUN_AS_UI:
    #         import gradio as gr
            
    #         with gr.Blocks() as demo:
    #             gr.Markdown("### Multi-Threaded Gradio Engine")
    #             output_box = gr.Textbox(label="RAG Pipeline Build Status", value="Ready.")
    #             start_btn = gr.Button("Run Pipeline")
                
    #             # Gradio automatically handles the 'yield' from ui_wrapper to stream text
    #             start_btn.click(fn=ui_wrapper, outputs=output_box)
                
    #         demo.launch()
    #     else:
    #         # Run standard standalone mode directly in the terminal
    #         all_main()
        
    
        
        

        


