# run from terminal * streamlit run streamlit_test.py *

import streamlit as st
import appNew_streamlit_test as RAGapp


st.title("Covid Guidance - RAG LLM")

# question = st.sidebar.text_input("Please type your Covid question quidance question, sources for the response include WHO, NHS and CDC sources.", type="password")

def generate_response(input_text):
    # model = ChatOpenAI(temperature=0.7, api_key=openai_api_key)
    # st.info(model.invoke(input_text))
    st.info("Great, that will be passed to the RAG for retrieval of relevant information, and a summary will be generated by the LLM")

with st.form("my_form"):
    text = st.text_area(
        "Enter text:",
        "Please type your Covid question quidance question, sources searched for the response include WHO, NHS and CDC sources?",
    )
    submitted = st.form_submit_button("Submit")

    if submitted:
        generate_response(text)
        
        
with st.form("my form"):
    # text = st.text_area(
    #         "Thanks, click submit to begin downloading of source documents"
    #     )
    st.write("Thanks, click submit to begin downloading of source documents")
    submitted = st.form_submit_button("Submit")

    if submitted:
        text = RAGapp.main_download_prepare_chunk()
        st.info(text)
        