# run from terminal * streamlit run streamlit_test.py *

import streamlit as st
import appNew_streamlit_test as RAGapp


st.title("Covid Guidance - RAG LLM")
user_question = "What are the primary safety guidelines regarding Covid?" # default unless user provides new one

question = st.sidebar.text_input("Hello :-)")

def generate_response(input_text):
    # st.info(model.invoke(input_text))
    st.info("Great, that will be passed to the RAG for retrieval of relevant information, and a summary will be generated by the LLM")
    return input_text
    
    
    

with st.form("my_form"):
    st.write("Please type in your Covid question quidance question below, or amend the question already.\nAvailable publications include information from the WHO, NHS and CDC sources.")
    
    text = st.text_area(
        "What are the primary safety guidelines regarding Covid?",
    )
    submitted = st.form_submit_button("Submit")

    if submitted:
        user_question = generate_response(text)
            
        # st.write("Thanks, click submit to begin downloading of source documents")
        # submitted = st.form_submit_button("Submit")

        # if submitted:
        st.info(f"Downloading, cleaning and preparing chunks:{text}")
        text, all_chunks = RAGapp.main_download_prepare_chunk()
        
        st.info(f"Generating and storing vectors:{text}")
        text, transformer_Model = RAGapp.main_generate_vectors_and_save(all_chunks)
        
        st.info("Retrieving contexts from vector store")
        str_Progress, combined_context = RAGapp.main_search_embeddings(user_question, transformer_Model, RAGapp.VECTOR_SEARCH_LIMIT)
        
        
        # str_Progress, combined_context = main_search_embeddings(user_question, transformer_Model, VECTOR_SEARCH_LIMIT)