# run from terminal * streamlit run streamlit_test.py *

import streamlit as st


st.title("Covid Guidance - RAG LLM")

# question = st.sidebar.text_input("Please type your Covid question quidance question, sources for the response include WHO, NHS and CDC sources.", type="password")

def generate_response(input_text):
    # model = ChatOpenAI(temperature=0.7, api_key=openai_api_key)
    # st.info(model.invoke(input_text))
    st.info("Great, that will be passed to the RAG for retrieval of relevant information, and a summary will be generated by the LLM")

with st.form("my_form"):
    text = st.text_area(
        "Enter text:",
        "Please type your Covid question quidance question, sources for the response include WHO, NHS and CDC sources?",
    )
    submitted = st.form_submit_button("Submit")
    # if not openai_api_key.startswith("sk-"):
    #     st.warning("Please enter your OpenAI API key!", icon="⚠")
    if submitted:
        generate_response(text)
        import appNew as appLLM