events { worker_connections 1024; }

http {
    # Main server listening on port 80 inside the container (mapped to 8080 outside)
    server {
        listen 80;

        # Route 1: Direct OpenAI/Ollama traffic (e.g., http://localhost:8080/v1/chat/completions)
        location /v1/ {
            proxy_pass http://ollama-service:11434/v1/; # here, only the incoming request url after the v1/ will be forwarded, the beginning (matched) part of the uirl will be replaced.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr; # passes the users’s real IP address down to ollama
            
            # Crucial for LLM streaming response stability
            proxy_http_version 1.1; # this line and the line below, together they tell nginx to keep a persistent connection alive, a single persistent connect to Ollama
            proxy_set_header Connection "";
            proxy_buffering off; # report back to browser, instantly piece by piece with LLM output
            proxy_read_timeout 3600s; # wait up to and hour as large LLMs can be slow
        }

        # Route 2: Direct MLflow traffic (e.g., http://localhost:8080/ajax-api/ or /api/)
        location / { # this acts as a catch all route for everything that isn’t going to be sent to Ollama
            proxy_pass http://mlflow-service:5000; # the full original request path will be sent onto mlflow.
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}